import {
    Search, MoreVertical, Camera, MessageSquare, Users, Phone,
    CircleDot, Lock, Archive, ArrowLeft, ArrowRight, Mic,
    Paperclip, Smile, Check, CheckCheck, Plus, History,
    Laptop, Video, Sun, Moon, PanelLeftOpen, ChevronRight,
    ChevronLeft, ChevronDown, Pin, Trash2, X, MessageCircle,
    Settings, Star, Users2, SquareCheck, MessageSquareText, LogOut,
    UserPlus, CheckSquare, Megaphone, Bell, BellOff as BellOffIcon, Send, Filter,
    Info, ImageOff, Forward, Share2, UserRound, FileText,
    AlertOctagon, HelpCircle, SunMoon, Wallpaper, Languages, Sparkles,
    ShieldCheck, MapPin, PhoneOff, UserX, Fingerprint, Eye,
    EyeOff, QrCode, Database, Globe, FolderOpen, PieChart,
    ArrowUpCircle, Pencil, User, Link, Link2, Flashlight,
    FlashlightOff, Image as ImageIcon, ArrowDownLeft, ArrowUpRight, Heart, Calendar,
    Smartphone, Monitor, Flag, GripVertical, Copy, Mail,
    Play, Pause, Download, Headphones, RefreshCw, Clock,
    Cloud, AlertTriangle, CheckCircle2, XCircle, PhoneMissed, Asterisk,
    Key, Navigation, Reply, UserMinus, Edit2, Rss,
    Radio, Pen, Edit, BarChart2, KeyRound, Settings2,
    CircleCheck, Palette, Type, HeartHandshake, HeartOff, AlertCircle,
    CheckCircle, Ban, RotateCcw, ListPlus, SearchX, Circle,
    MoreHorizontal, ExternalLink, Bookmark, Volume2, File, Music,
    ChevronUp, Tag, VolumeX, MicOff, VideoOff,
} from 'lucide-react';

export const Icons = {
    Search, MoreVertical, Camera, MessageSquare, Users, Phone, CircleDot, Lock,
    Archive, ArrowLeft, Mic, Paperclip, Smile, Check, CheckCheck, Plus, History,
    Laptop, Video, Sun, Moon, PanelLeftOpen, ChevronRight, ChevronLeft, ChevronDown,
    Pin, Trash2, X, MessageCircle, Settings, Star, Users2, SquareCheck,
    MessageSquareText, LogOut, UserPlus, CheckSquare, Megaphone, Bell, Send,
    Filter, Info, ImageOff, Forward, Share2, UserRound, FileText, AlertOctagon,
    HelpCircle, SunMoon, Wallpaper, Languages, Sparkles, ShieldCheck, MapPin,
    PhoneOff, UserX, Fingerprint, Eye, EyeOff, QrCode, Database, Globe, FolderOpen,
    PieChart, ArrowUpCircle, Pencil, User, Link, Link2, Flashlight, FlashlightOff,
    Image: ImageIcon, ArrowDownLeft, ArrowUpRight, Heart, Calendar, Smartphone,
    Monitor, Flag, GripVertical, Copy, Mail, Play, Pause, Download, Headphones,
    RefreshCw, Clock, Cloud, AlertTriangle, CheckCircle2, XCircle, PhoneMissed,
    Asterisk, Key, Navigation, Reply, UserMinus, Edit2, Rss, Radio, Pen, Edit,
    BarChart2, KeyRound, Settings2, CircleCheck,
    ArrowRight, Palette, Type, Tag,
    HeartHandshake, HeartOff, AlertCircle, CheckCircle, Ban, RotateCcw,
    // New icons needed by components
    Circle, MoreHorizontal, ExternalLink, Bookmark, Volume2, File, Music,
    // Aliases
    CheckAll: CheckCheck,
    Ad: Megaphone,
    Status: Star,
    Trash: Trash2,
    BellOff: BellOffIcon,
    ArchiveRestore: Archive,
    List: ListPlus,
    MicOff,
    VideoOff,
    VolumeX,
    ChevronUp,
    SearchX,
    ListPlus,
};

export default Icons;
